# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180727_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('gtitle', models.CharField(max_length=20)),
                ('gpic', models.CharField(max_length=200)),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gunit', models.CharField(default='500g', max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_goods',
            },
        ),
    ]
